### ISSUE TITLE
急需文档说明。。。

### ISSUE THREAD

**Issue by wond-z** [jokechat/yii-dingtalk#1]
请作者说明详细安装使用方法，初学者。。。

**Comment by jokechat** [comment]
这段时间个人私事比较多，文档没有继续写下去，月底有时间我继续完善下，急用的话给我jokechat@qq.com 发邮件，我帮配置一下，
基于yii框架做的  dingtalk api的进一步封装，isv没有对接成功

认真看下  modules模块下的test文件夹，里面是一些对封装接口的调用
